# Generated by Codex for reliable concurrent task submission.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environment', '0022_climatedatafile_direct_formats'),
    ]

    operations = [
        migrations.AddField(
            model_name='processingtask', name='active_fingerprint',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='活跃任务指纹'),
        ),
        migrations.AddField(
            model_name='processingtask', name='celery_task_id',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Celery任务ID'),
        ),
        migrations.AddField(
            model_name='processingtask', name='dispatch_attempts',
            field=models.PositiveIntegerField(default=0, verbose_name='投递尝试次数'),
        ),
        migrations.AddField(
            model_name='processingtask', name='dispatch_status',
            field=models.CharField(choices=[('pending', '待投递'), ('dispatched', '已投递'), ('failed', '投递失败')], default='pending', max_length=20, verbose_name='投递状态'),
        ),
        migrations.AddField(
            model_name='processingtask', name='idempotency_key',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True, verbose_name='幂等请求键'),
        ),
        migrations.AddField(
            model_name='processingtask', name='last_dispatch_error',
            field=models.TextField(blank=True, default='', verbose_name='最近投递错误'),
        ),
        migrations.AddField(
            model_name='processingtask', name='priority',
            field=models.CharField(choices=[('high', '高'), ('normal', '普通'), ('low', '低')], default='normal', max_length=10, verbose_name='任务优先级'),
        ),
        migrations.AddField(
            model_name='processingtask', name='queue_name',
            field=models.CharField(default='geo.default', max_length=32, verbose_name='队列名称'),
        ),
        migrations.AddField(
            model_name='processingtask', name='request_fingerprint',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='请求指纹'),
        ),
        migrations.AddIndex(
            model_name='processingtask',
            index=models.Index(fields=['status', 'priority', 'created_at'], name='processing_task_queue_idx'),
        ),
        migrations.AddIndex(
            model_name='processingtask',
            index=models.Index(fields=['dispatch_status', 'created_at'], name='processing_task_dispatch_idx'),
        ),
    ]
