# Generated by Codex for the durable ecological-task outbox.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environment', '0023_processingtask_concurrency_controls'),
    ]

    operations = [
        migrations.AddField(
            model_name='processingtask',
            name='request_payload',
            field=models.JSONField(blank=True, default=dict, verbose_name='任务请求参数'),
        ),
        migrations.AlterField(
            model_name='processingtask',
            name='dispatch_status',
            field=models.CharField(
                choices=[
                    ('pending', '待投递'),
                    ('dispatching', '投递中'),
                    ('dispatched', '已投递'),
                    ('failed', '投递失败'),
                ],
                default='pending',
                max_length=20,
                verbose_name='投递状态',
            ),
        ),
    ]
