# Generated by Codex for stale outbox-claim recovery.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environment', '0024_processingtask_request_payload_and_dispatching'),
    ]

    operations = [
        migrations.AddField(
            model_name='processingtask',
            name='dispatching_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最近投递认领时间'),
        ),
    ]
